#From https://github.com/ProjectHDS/Herodotus/blob/master/.github/workflows/dev.yml

name: black
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  BUILD: Magier
  VERSION: 1.0-Alpha

jobs:
  FTBQuestsProcessor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Run FTB Quests lang processor
        run: python runners/ftbq_lang_processor.py

      - name: Commit processor changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: ikexing
          author_email: ikexing.cn@gmail.com
          message: "ftbq lang processor changes (github action)"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

  CreateCursePack:
    runs-on: ubuntu-latest
    needs: FTBQuestsProcessor
    steps:
      - uses: actions/checkout@v2
      
      - name: Run build.sh
        run: bash runners/build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD }}-${{ env.VERSION }}-update${{ github.run_number }}
          path: artifacts